name: Déploiement Portfolio GitHub Pages

on:
  push:
    branches:
      - main  # Change en 'master' si ta branche s'appelle master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Déploiement via GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
